drop TABLE  IF EXISTS STORK_BASICS;

create table STORK_BASICS
(
	ID bigint not null auto_increment comment '自增主键' primary key,
	STOCK_CODE varchar(16) default '0' not null comment '代码',
	NAME varchar(32) default '0' not null comment '名称',
	INDUSTRY varchar(32) default '0' not null comment '所属行业',
	AREA varchar(16) default '0' not null comment '地区',
	PE DECIMAL(10, 2) default 0 not null comment '市盈率',
	OUTSTANDING DECIMAL(10, 2) default 0 not null comment '流通股本（亿）',
	TOTALS DECIMAL(10, 2) default 0 not null comment '总股本（亿）',
	TOTAL_ASSETS DECIMAL(16, 2) default 0 not null comment '总资产(万)',
	LIQUID_ASSETS DECIMAL(16, 2) default 0 not null comment '流动资产',
	FIXED_ASSETS DECIMAL(16, 2) default 0 not null comment '固定资产',
	RESERVED DECIMAL(16, 2) default 0 not null comment '公积金',
	RESERVED_PERSHARE DECIMAL(10, 2) default 0 not null comment '每股公积金',
	ESP DECIMAL(16, 2) default 0 not null comment '每股收益',
	BVPS DECIMAL(16, 2) default 0 not null comment '每股净资',
	PB DECIMAL(16, 2) default 0 not null comment '市净率',
	TIMETO_MARKET VARCHAR(16) not null default '0' comment '上市日期',
	UNDP DECIMAL(16, 2) not null default 0 comment '未分利润',
	PER_UNDP DECIMAL(16, 2) not null default 0 comment '每股未分配',
	REV DECIMAL(16, 2) not null default 0 comment '收入同比',
	PROFIT DECIMAL(16, 2) not null default 0 comment '利润同比',
	GPR DECIMAL(16, 2) not null default 0 comment '毛利率',
	NPR DECIMAL(16, 2) not null default 0 comment '净利润率',
	HOLDERS DECIMAL(16, 2) not null default 0 comment '股东人数',
	STOCK_TYPE varchar(8) not null default '' comment '股票类型',
	VERSION int not null default 0 comment '版本',
	UPDATED  TIMESTAMP not null default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	CREATED DATETIME NOT NULL DEFAULT '1970-01-01' COMMENT '创建时间',
	KEY `IDX_STOCK_CODE` (`STOCK_CODE`)

)
comment '股票列表'
;

drop TABLE  IF EXISTS HIST_DATA_D;

create table HIST_DATA_D
(
	ID bigint not null auto_increment comment '自增主键' primary key,
	STOCK_CODE varchar(16) default '0' not null comment '代码',
	DATE_IN DATETIME default '1970-01-01' not null comment '日期',
	DAY_IN DATE default '1000-01-01' not null comment '日期',
	OPEN DECIMAL(16, 3) default 0 not null comment '开盘价',
	HIGH DECIMAL(16, 3) default 0 not null comment '最高价',
	CLOSE DECIMAL(16, 3) default 0 not null comment '收盘价',
	LOW DECIMAL(16, 3) default 0 not null comment '最低价',
	VOLUME DECIMAL(10, 2) default 0 not null comment '成交量',
	PRIVE_CHANGE DECIMAL(10, 2) default 0 not null comment '价格变动',
	P_CHANGE DECIMAL(16, 2) default 0 not null comment '涨跌幅',
	MA5 DECIMAL(16, 4) default 0 not null comment '5日均价',
	MA10 DECIMAL(16, 4) default 0 not null comment '10日均价',
	MA20 DECIMAL(16, 4) default 0 not null comment '20日均价',
	V_MA5 DECIMAL(10, 2) default 0 not null comment '5日均量',
	V_MA10 DECIMAL(16, 2) default 0 not null comment '10日均量',
	V_MA20 DECIMAL(16, 2) default 0 not null comment '20日均量',
	TURN_OVER DECIMAL(8, 2) default 0 not null comment '换手率',
	MIN_PRICE DECIMAL(16, 4) default 0 not null,
MAX_PRICE DECIMAL(16, 4) default 0 not null,
VAR_PRICE DECIMAL(16, 4) default 0 not null,
VAR_PRICE_3D DECIMAL(16, 4) default 0 not null,
MA30 DECIMAL(16, 4) default 0 not null,
MA60 DECIMAL(16, 4) default 0 not null,
VMA30 DECIMAL(16, 4) default 0 not null,
VMA60 DECIMAL(16, 4) default 0 not null,
MID_PRICE DECIMAL(16, 4) default 0 not null,
OPEN_DEV_MA5 DECIMAL(16, 4) default 0 not null,
OPEN_DEV_MA10 DECIMAL(16, 4) default 0 not null,
CLOSE_DEV_MA5 DECIMAL(16, 4) default 0 not null,
CLOSE_DEV_MA10 DECIMAL(16, 4) default 0 not null,
DIFF DECIMAL(16, 4) default 0 not null,
DEA DECIMAL(16, 4) default 0 not null,
MACD DECIMAL(16, 4) default 0 not null,
BOLL_LOW DECIMAL(16, 4) default 0 not null,
BOLL_UP DECIMAL(16, 4) default 0 not null,
BOLL_RELATIVE DECIMAL(16, 4) default 0 not null,
DIVIDEND_IND DECIMAL(16, 4) default 0 not null,
REL_1Y DECIMAL(16, 4) default 0 not null,
REL_6M DECIMAL(16, 4) default 0 not null,
REL_3M DECIMAL(16, 4) default 0 not null,
REL_1M DECIMAL(16, 4) default 0 not null,
REL_2W DECIMAL(16, 4) default 0 not null,
REL_5D DECIMAL(16, 4) default 0 not null,
EMA5 DECIMAL(16, 4) default 0 not null,
EMA10 DECIMAL(16, 4) default 0 not null,
EMA20 DECIMAL(16, 4) default 0 not null,
EMA30 DECIMAL(16, 4) default 0 not null,
EMA60 DECIMAL(16, 4) default 0 not null,
MA_RANGE DECIMAL(16, 4) default 0 not null,
EMA60_POS DECIMAL(16, 4) default 0 not null,
V_DIFF0 DECIMAL(16, 4) default 0 not null,
V_DIFF1 DECIMAL(16, 4) default 0 not null,
V_DIFF2 DECIMAL(16, 4) default 0 not null,
V_DIFF3 DECIMAL(16, 4) default 0 not null,
V_DIFF4 DECIMAL(16, 4) default 0 not null,
V_DIFF5 DECIMAL(16, 4) default 0 not null,
RSI DECIMAL(16, 4) default 0 not null,
REL_1M_V DECIMAL(16, 4) default 0 not null,
REL_2W_V DECIMAL(16, 4) default 0 not null,
REL_5D_V DECIMAL(16, 4) default 0 not null,
REL_8W_VAR DECIMAL(16, 4) default 0 not null,
REL_4W_VAR DECIMAL(16, 4) default 0 not null,
REL_2W_VAR DECIMAL(16, 4) default 0 not null,
	DECISION varchar(16) default '0' not null comment '决策',
	VERSION int not null default 0 comment '版本',
	UPDATED  TIMESTAMP not null default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	CREATED DATETIME NOT NULL DEFAULT '1970-01-01' COMMENT '创建时间',
	KEY `IDX_STOCK_CODE` (`STOCK_CODE`)

)
comment '股票历史信息'
;
drop TABLE  IF EXISTS HIST_DATA_W;
create table HIST_DATA_W
(
	ID bigint not null auto_increment comment '自增主键' primary key,
	STOCK_CODE varchar(16) default '0' not null comment '代码',
	DATE_IN DATETIME default '1970-01-01' not null comment '日期',
	DAY_IN DATE default '1000-01-01' not null comment '日期',
	OPEN DECIMAL(16, 3) default 0 not null comment '开盘价',
	HIGH DECIMAL(16, 3) default 0 not null comment '最高价',
	CLOSE DECIMAL(16, 3) default 0 not null comment '收盘价',
	LOW DECIMAL(16, 3) default 0 not null comment '最低价',
	VOLUME DECIMAL(10, 2) default 0 not null comment '成交量',
	PRIVE_CHANGE DECIMAL(10, 2) default 0 not null comment '价格变动',
	P_CHANGE DECIMAL(16, 2) default 0 not null comment '涨跌幅',
	MA5 DECIMAL(16, 4) default 0 not null comment '5日均价',
	MA10 DECIMAL(16, 4) default 0 not null comment '10日均价',
	MA20 DECIMAL(16, 4) default 0 not null comment '20日均价',
	V_MA5 DECIMAL(10, 2) default 0 not null comment '5日均量',
	V_MA10 DECIMAL(16, 2) default 0 not null comment '10日均量',
	V_MA20 DECIMAL(16, 2) default 0 not null comment '20日均量',
	TURN_OVER DECIMAL(8, 2) default 0 not null comment '换手率',
	MIN_PRICE DECIMAL(16, 4) default 0 not null,
MAX_PRICE DECIMAL(16, 4) default 0 not null,
VAR_PRICE DECIMAL(16, 4) default 0 not null,
VAR_PRICE_3D DECIMAL(16, 4) default 0 not null,
MA30 DECIMAL(16, 4) default 0 not null,
MA60 DECIMAL(16, 4) default 0 not null,
VMA30 DECIMAL(16, 4) default 0 not null,
VMA60 DECIMAL(16, 4) default 0 not null,
MID_PRICE DECIMAL(16, 4) default 0 not null,
OPEN_DEV_MA5 DECIMAL(16, 4) default 0 not null,
OPEN_DEV_MA10 DECIMAL(16, 4) default 0 not null,
CLOSE_DEV_MA5 DECIMAL(16, 4) default 0 not null,
CLOSE_DEV_MA10 DECIMAL(16, 4) default 0 not null,
DIFF DECIMAL(16, 4) default 0 not null,
DEA DECIMAL(16, 4) default 0 not null,
MACD DECIMAL(16, 4) default 0 not null,
BOLL_LOW DECIMAL(16, 4) default 0 not null,
BOLL_UP DECIMAL(16, 4) default 0 not null,
BOLL_RELATIVE DECIMAL(16, 4) default 0 not null,
DIVIDEND_IND DECIMAL(16, 4) default 0 not null,
REL_1Y DECIMAL(16, 4) default 0 not null,
REL_6M DECIMAL(16, 4) default 0 not null,
REL_3M DECIMAL(16, 4) default 0 not null,
REL_1M DECIMAL(16, 4) default 0 not null,
REL_2W DECIMAL(16, 4) default 0 not null,
REL_5D DECIMAL(16, 4) default 0 not null,
EMA5 DECIMAL(16, 4) default 0 not null,
EMA10 DECIMAL(16, 4) default 0 not null,
EMA20 DECIMAL(16, 4) default 0 not null,
EMA30 DECIMAL(16, 4) default 0 not null,
EMA60 DECIMAL(16, 4) default 0 not null,
MA_RANGE DECIMAL(16, 4) default 0 not null,
EMA60_POS DECIMAL(16, 4) default 0 not null,
V_DIFF0 DECIMAL(16, 4) default 0 not null,
V_DIFF1 DECIMAL(16, 4) default 0 not null,
V_DIFF2 DECIMAL(16, 4) default 0 not null,
V_DIFF3 DECIMAL(16, 4) default 0 not null,
V_DIFF4 DECIMAL(16, 4) default 0 not null,
V_DIFF5 DECIMAL(16, 4) default 0 not null,
RSI DECIMAL(16, 4) default 0 not null,
REL_1M_V DECIMAL(16, 4) default 0 not null,
REL_2W_V DECIMAL(16, 4) default 0 not null,
REL_5D_V DECIMAL(16, 4) default 0 not null,
REL_8W_VAR DECIMAL(16, 4) default 0 not null,
REL_4W_VAR DECIMAL(16, 4) default 0 not null,
REL_2W_VAR DECIMAL(16, 4) default 0 not null,
	DECISION varchar(16) default '0' not null comment '决策',
	VERSION int not null default 0 comment '版本',
	UPDATED  TIMESTAMP not null default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	CREATED DATETIME NOT NULL DEFAULT '1970-01-01' COMMENT '创建时间',
	KEY `IDX_STOCK_CODE` (`STOCK_CODE`)

)
comment '股票历史信息'
;
drop TABLE  IF EXISTS HIST_DATA_M;
create table HIST_DATA_M
(
	ID bigint not null auto_increment comment '自增主键' primary key,
	STOCK_CODE varchar(16) default '0' not null comment '代码',
	DATE_IN DATETIME default '1970-01-01' not null comment '日期',
	DAY_IN DATE default '1000-01-01' not null comment '日期',
	OPEN DECIMAL(16, 3) default 0 not null comment '开盘价',
	HIGH DECIMAL(16, 3) default 0 not null comment '最高价',
	CLOSE DECIMAL(16, 3) default 0 not null comment '收盘价',
	LOW DECIMAL(16, 3) default 0 not null comment '最低价',
	VOLUME DECIMAL(10, 2) default 0 not null comment '成交量',
	PRIVE_CHANGE DECIMAL(10, 2) default 0 not null comment '价格变动',
	P_CHANGE DECIMAL(16, 2) default 0 not null comment '涨跌幅',
	MA5 DECIMAL(16, 4) default 0 not null comment '5日均价',
	MA10 DECIMAL(16, 4) default 0 not null comment '10日均价',
	MA20 DECIMAL(16, 4) default 0 not null comment '20日均价',
	V_MA5 DECIMAL(10, 2) default 0 not null comment '5日均量',
	V_MA10 DECIMAL(16, 2) default 0 not null comment '10日均量',
	V_MA20 DECIMAL(16, 2) default 0 not null comment '20日均量',
	TURN_OVER DECIMAL(16, 2) default 0 not null comment '换手率',
	MIN_PRICE DECIMAL(16, 4) default 0 not null,
MAX_PRICE DECIMAL(16, 4) default 0 not null,
VAR_PRICE DECIMAL(16, 4) default 0 not null,
VAR_PRICE_3D DECIMAL(16, 4) default 0 not null,
MA30 DECIMAL(16, 4) default 0 not null,
MA60 DECIMAL(16, 4) default 0 not null,
VMA30 DECIMAL(16, 4) default 0 not null,
VMA60 DECIMAL(16, 4) default 0 not null,
MID_PRICE DECIMAL(16, 4) default 0 not null,
OPEN_DEV_MA5 DECIMAL(16, 4) default 0 not null,
OPEN_DEV_MA10 DECIMAL(16, 4) default 0 not null,
CLOSE_DEV_MA5 DECIMAL(16, 4) default 0 not null,
CLOSE_DEV_MA10 DECIMAL(16, 4) default 0 not null,
DIFF DECIMAL(16, 4) default 0 not null,
DEA DECIMAL(16, 4) default 0 not null,
MACD DECIMAL(16, 4) default 0 not null,
BOLL_LOW DECIMAL(16, 4) default 0 not null,
BOLL_UP DECIMAL(16, 4) default 0 not null,
BOLL_RELATIVE DECIMAL(16, 4) default 0 not null,
DIVIDEND_IND DECIMAL(16, 4) default 0 not null,
REL_1Y DECIMAL(16, 4) default 0 not null,
REL_6M DECIMAL(16, 4) default 0 not null,
REL_3M DECIMAL(16, 4) default 0 not null,
REL_1M DECIMAL(16, 4) default 0 not null,
REL_2W DECIMAL(16, 4) default 0 not null,
REL_5D DECIMAL(16, 4) default 0 not null,
EMA5 DECIMAL(16, 4) default 0 not null,
EMA10 DECIMAL(16, 4) default 0 not null,
EMA20 DECIMAL(16, 4) default 0 not null,
EMA30 DECIMAL(16, 4) default 0 not null,
EMA60 DECIMAL(16, 4) default 0 not null,
MA_RANGE DECIMAL(16, 4) default 0 not null,
EMA60_POS DECIMAL(16, 4) default 0 not null,
V_DIFF0 DECIMAL(16, 4) default 0 not null,
V_DIFF1 DECIMAL(16, 4) default 0 not null,
V_DIFF2 DECIMAL(16, 4) default 0 not null,
V_DIFF3 DECIMAL(16, 4) default 0 not null,
V_DIFF4 DECIMAL(16, 4) default 0 not null,
V_DIFF5 DECIMAL(16, 4) default 0 not null,
RSI DECIMAL(16, 4) default 0 not null,
REL_1M_V DECIMAL(16, 4) default 0 not null,
REL_2W_V DECIMAL(16, 4) default 0 not null,
REL_5D_V DECIMAL(16, 4) default 0 not null,
REL_8W_VAR DECIMAL(16, 4) default 0 not null,
REL_4W_VAR DECIMAL(16, 4) default 0 not null,
REL_2W_VAR DECIMAL(16, 4) default 0 not null,
	DECISION varchar(16) default '0' not null comment '决策',
	VERSION int not null default 0 comment '版本',
	UPDATED  TIMESTAMP not null default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	CREATED DATETIME NOT NULL DEFAULT '1970-01-01' COMMENT '创建时间',
	KEY `IDX_STOCK_CODE` (`STOCK_CODE`)

)
comment '股票历史信息'
;

drop TABLE  IF EXISTS HIST_DATA_5;

create table HIST_DATA_5
(
	ID bigint not null auto_increment comment '自增主键' primary key,
	STOCK_CODE varchar(16) default '0' not null comment '代码',
	DATE_IN DATETIME default '1970-01-01' not null comment '日期',
	DAY_IN DATE default '1000-01-01' not null comment '日期',
	OPEN DECIMAL(16, 3) default 0 not null comment '开盘价',
	HIGH DECIMAL(16, 3) default 0 not null comment '最高价',
	CLOSE DECIMAL(16, 3) default 0 not null comment '收盘价',
	LOW DECIMAL(16, 3) default 0 not null comment '最低价',
	VOLUME DECIMAL(10, 2) default 0 not null comment '成交量',
	PRIVE_CHANGE DECIMAL(10, 2) default 0 not null comment '价格变动',
	P_CHANGE DECIMAL(16, 2) default 0 not null comment '涨跌幅',
	MA5 DECIMAL(16, 4) default 0 not null comment '5日均价',
	MA10 DECIMAL(16, 4) default 0 not null comment '10日均价',
	MA20 DECIMAL(16, 4) default 0 not null comment '20日均价',
	V_MA5 DECIMAL(10, 2) default 0 not null comment '5日均量',
	V_MA10 DECIMAL(16, 2) default 0 not null comment '10日均量',
	V_MA20 DECIMAL(16, 2) default 0 not null comment '20日均量',
	TURN_OVER DECIMAL(8, 2) default 0 not null comment '换手率',
	MIN_PRICE DECIMAL(16, 4) default 0 not null,
MAX_PRICE DECIMAL(16, 4) default 0 not null,
VAR_PRICE DECIMAL(16, 4) default 0 not null,
VAR_PRICE_3D DECIMAL(16, 4) default 0 not null,
MA30 DECIMAL(16, 4) default 0 not null,
MA60 DECIMAL(16, 4) default 0 not null,
VMA30 DECIMAL(16, 4) default 0 not null,
VMA60 DECIMAL(16, 4) default 0 not null,
MID_PRICE DECIMAL(16, 4) default 0 not null,
OPEN_DEV_MA5 DECIMAL(16, 4) default 0 not null,
OPEN_DEV_MA10 DECIMAL(16, 4) default 0 not null,
CLOSE_DEV_MA5 DECIMAL(16, 4) default 0 not null,
CLOSE_DEV_MA10 DECIMAL(16, 4) default 0 not null,
DIFF DECIMAL(16, 4) default 0 not null,
DEA DECIMAL(16, 4) default 0 not null,
MACD DECIMAL(16, 4) default 0 not null,
BOLL_LOW DECIMAL(16, 4) default 0 not null,
BOLL_UP DECIMAL(16, 4) default 0 not null,
BOLL_RELATIVE DECIMAL(16, 4) default 0 not null,
DIVIDEND_IND DECIMAL(16, 4) default 0 not null,
REL_1Y DECIMAL(16, 4) default 0 not null,
REL_6M DECIMAL(16, 4) default 0 not null,
REL_3M DECIMAL(16, 4) default 0 not null,
REL_1M DECIMAL(16, 4) default 0 not null,
REL_2W DECIMAL(16, 4) default 0 not null,
REL_5D DECIMAL(16, 4) default 0 not null,
EMA5 DECIMAL(16, 4) default 0 not null,
EMA10 DECIMAL(16, 4) default 0 not null,
EMA20 DECIMAL(16, 4) default 0 not null,
EMA30 DECIMAL(16, 4) default 0 not null,
EMA60 DECIMAL(16, 4) default 0 not null,
MA_RANGE DECIMAL(16, 4) default 0 not null,
EMA60_POS DECIMAL(16, 4) default 0 not null,
V_DIFF0 DECIMAL(16, 4) default 0 not null,
V_DIFF1 DECIMAL(16, 4) default 0 not null,
V_DIFF2 DECIMAL(16, 4) default 0 not null,
V_DIFF3 DECIMAL(16, 4) default 0 not null,
V_DIFF4 DECIMAL(16, 4) default 0 not null,
V_DIFF5 DECIMAL(16, 4) default 0 not null,
RSI DECIMAL(16, 4) default 0 not null,
REL_1M_V DECIMAL(16, 4) default 0 not null,
REL_2W_V DECIMAL(16, 4) default 0 not null,
REL_5D_V DECIMAL(16, 4) default 0 not null,
REL_8W_VAR DECIMAL(16, 4) default 0 not null,
REL_4W_VAR DECIMAL(16, 4) default 0 not null,
REL_2W_VAR DECIMAL(16, 4) default 0 not null,
	DECISION varchar(16) default '0' not null comment '决策',
	VERSION int not null default 0 comment '版本',
	UPDATED  TIMESTAMP not null default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	CREATED DATETIME NOT NULL DEFAULT '1970-01-01' COMMENT '创建时间',
	KEY `IDX_STOCK_CODE` (`STOCK_CODE`)

)
comment '股票历史信息'
;

drop TABLE  IF EXISTS HIST_DATA_15;

create table HIST_DATA_15
(
	ID bigint not null auto_increment comment '自增主键' primary key,
	STOCK_CODE varchar(16) default '0' not null comment '代码',
	DATE_IN DATETIME default '1970-01-01' not null comment '日期',
	DAY_IN DATE default '1000-01-01' not null comment '日期',
	OPEN DECIMAL(16, 3) default 0 not null comment '开盘价',
	HIGH DECIMAL(16, 3) default 0 not null comment '最高价',
	CLOSE DECIMAL(16, 3) default 0 not null comment '收盘价',
	LOW DECIMAL(16, 3) default 0 not null comment '最低价',
	VOLUME DECIMAL(10, 2) default 0 not null comment '成交量',
	PRIVE_CHANGE DECIMAL(10, 2) default 0 not null comment '价格变动',
	P_CHANGE DECIMAL(16, 2) default 0 not null comment '涨跌幅',
	MA5 DECIMAL(16, 4) default 0 not null comment '5日均价',
	MA10 DECIMAL(16, 4) default 0 not null comment '10日均价',
	MA20 DECIMAL(16, 4) default 0 not null comment '20日均价',
	V_MA5 DECIMAL(10, 2) default 0 not null comment '5日均量',
	V_MA10 DECIMAL(16, 2) default 0 not null comment '10日均量',
	V_MA20 DECIMAL(16, 2) default 0 not null comment '20日均量',
	TURN_OVER DECIMAL(8, 2) default 0 not null comment '换手率',
	MIN_PRICE DECIMAL(16, 4) default 0 not null,
MAX_PRICE DECIMAL(16, 4) default 0 not null,
VAR_PRICE DECIMAL(16, 4) default 0 not null,
VAR_PRICE_3D DECIMAL(16, 4) default 0 not null,
MA30 DECIMAL(16, 4) default 0 not null,
MA60 DECIMAL(16, 4) default 0 not null,
VMA30 DECIMAL(16, 4) default 0 not null,
VMA60 DECIMAL(16, 4) default 0 not null,
MID_PRICE DECIMAL(16, 4) default 0 not null,
OPEN_DEV_MA5 DECIMAL(16, 4) default 0 not null,
OPEN_DEV_MA10 DECIMAL(16, 4) default 0 not null,
CLOSE_DEV_MA5 DECIMAL(16, 4) default 0 not null,
CLOSE_DEV_MA10 DECIMAL(16, 4) default 0 not null,
DIFF DECIMAL(16, 4) default 0 not null,
DEA DECIMAL(16, 4) default 0 not null,
MACD DECIMAL(16, 4) default 0 not null,
BOLL_LOW DECIMAL(16, 4) default 0 not null,
BOLL_UP DECIMAL(16, 4) default 0 not null,
BOLL_RELATIVE DECIMAL(16, 4) default 0 not null,
DIVIDEND_IND DECIMAL(16, 4) default 0 not null,
REL_1Y DECIMAL(16, 4) default 0 not null,
REL_6M DECIMAL(16, 4) default 0 not null,
REL_3M DECIMAL(16, 4) default 0 not null,
REL_1M DECIMAL(16, 4) default 0 not null,
REL_2W DECIMAL(16, 4) default 0 not null,
REL_5D DECIMAL(16, 4) default 0 not null,
EMA5 DECIMAL(16, 4) default 0 not null,
EMA10 DECIMAL(16, 4) default 0 not null,
EMA20 DECIMAL(16, 4) default 0 not null,
EMA30 DECIMAL(16, 4) default 0 not null,
EMA60 DECIMAL(16, 4) default 0 not null,
MA_RANGE DECIMAL(16, 4) default 0 not null,
EMA60_POS DECIMAL(16, 4) default 0 not null,
V_DIFF0 DECIMAL(16, 4) default 0 not null,
V_DIFF1 DECIMAL(16, 4) default 0 not null,
V_DIFF2 DECIMAL(16, 4) default 0 not null,
V_DIFF3 DECIMAL(16, 4) default 0 not null,
V_DIFF4 DECIMAL(16, 4) default 0 not null,
V_DIFF5 DECIMAL(16, 4) default 0 not null,
RSI DECIMAL(16, 4) default 0 not null,
REL_1M_V DECIMAL(16, 4) default 0 not null,
REL_2W_V DECIMAL(16, 4) default 0 not null,
REL_5D_V DECIMAL(16, 4) default 0 not null,
REL_8W_VAR DECIMAL(16, 4) default 0 not null,
REL_4W_VAR DECIMAL(16, 4) default 0 not null,
REL_2W_VAR DECIMAL(16, 4) default 0 not null,
	DECISION varchar(16) default '0' not null comment '决策',
	VERSION int not null default 0 comment '版本',
	UPDATED  TIMESTAMP not null default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	CREATED DATETIME NOT NULL DEFAULT '1970-01-01' COMMENT '创建时间',
	KEY `IDX_STOCK_CODE` (`STOCK_CODE`)

)
comment '股票历史信息'
;
drop TABLE  IF EXISTS HIST_DATA_30;

create table HIST_DATA_30
(
	ID bigint not null auto_increment comment '自增主键' primary key,
	STOCK_CODE varchar(16) default '0' not null comment '代码',
	DATE_IN DATETIME default '1970-01-01' not null comment '日期',
	DAY_IN DATE default '1000-01-01' not null comment '日期',
	OPEN DECIMAL(16, 3) default 0 not null comment '开盘价',
	HIGH DECIMAL(16, 3) default 0 not null comment '最高价',
	CLOSE DECIMAL(16, 3) default 0 not null comment '收盘价',
	LOW DECIMAL(16, 3) default 0 not null comment '最低价',
	VOLUME DECIMAL(10, 2) default 0 not null comment '成交量',
	PRIVE_CHANGE DECIMAL(10, 2) default 0 not null comment '价格变动',
	P_CHANGE DECIMAL(16, 2) default 0 not null comment '涨跌幅',
	MA5 DECIMAL(16, 4) default 0 not null comment '5日均价',
	MA10 DECIMAL(16, 4) default 0 not null comment '10日均价',
	MA20 DECIMAL(16, 4) default 0 not null comment '20日均价',
	V_MA5 DECIMAL(10, 2) default 0 not null comment '5日均量',
	V_MA10 DECIMAL(16, 2) default 0 not null comment '10日均量',
	V_MA20 DECIMAL(16, 2) default 0 not null comment '20日均量',
	TURN_OVER DECIMAL(8, 2) default 0 not null comment '换手率',
	MIN_PRICE DECIMAL(16, 4) default 0 not null,
MAX_PRICE DECIMAL(16, 4) default 0 not null,
VAR_PRICE DECIMAL(16, 4) default 0 not null,
VAR_PRICE_3D DECIMAL(16, 4) default 0 not null,
MA30 DECIMAL(16, 4) default 0 not null,
MA60 DECIMAL(16, 4) default 0 not null,
VMA30 DECIMAL(16, 4) default 0 not null,
VMA60 DECIMAL(16, 4) default 0 not null,
MID_PRICE DECIMAL(16, 4) default 0 not null,
OPEN_DEV_MA5 DECIMAL(16, 4) default 0 not null,
OPEN_DEV_MA10 DECIMAL(16, 4) default 0 not null,
CLOSE_DEV_MA5 DECIMAL(16, 4) default 0 not null,
CLOSE_DEV_MA10 DECIMAL(16, 4) default 0 not null,
DIFF DECIMAL(16, 4) default 0 not null,
DEA DECIMAL(16, 4) default 0 not null,
MACD DECIMAL(16, 4) default 0 not null,
BOLL_LOW DECIMAL(16, 4) default 0 not null,
BOLL_UP DECIMAL(16, 4) default 0 not null,
BOLL_RELATIVE DECIMAL(16, 4) default 0 not null,
DIVIDEND_IND DECIMAL(16, 4) default 0 not null,
REL_1Y DECIMAL(16, 4) default 0 not null,
REL_6M DECIMAL(16, 4) default 0 not null,
REL_3M DECIMAL(16, 4) default 0 not null,
REL_1M DECIMAL(16, 4) default 0 not null,
REL_2W DECIMAL(16, 4) default 0 not null,
REL_5D DECIMAL(16, 4) default 0 not null,
EMA5 DECIMAL(16, 4) default 0 not null,
EMA10 DECIMAL(16, 4) default 0 not null,
EMA20 DECIMAL(16, 4) default 0 not null,
EMA30 DECIMAL(16, 4) default 0 not null,
EMA60 DECIMAL(16, 4) default 0 not null,
MA_RANGE DECIMAL(16, 4) default 0 not null,
EMA60_POS DECIMAL(16, 4) default 0 not null,
V_DIFF0 DECIMAL(16, 4) default 0 not null,
V_DIFF1 DECIMAL(16, 4) default 0 not null,
V_DIFF2 DECIMAL(16, 4) default 0 not null,
V_DIFF3 DECIMAL(16, 4) default 0 not null,
V_DIFF4 DECIMAL(16, 4) default 0 not null,
V_DIFF5 DECIMAL(16, 4) default 0 not null,
RSI DECIMAL(16, 4) default 0 not null,
REL_1M_V DECIMAL(16, 4) default 0 not null,
REL_2W_V DECIMAL(16, 4) default 0 not null,
REL_5D_V DECIMAL(16, 4) default 0 not null,
REL_8W_VAR DECIMAL(16, 4) default 0 not null,
REL_4W_VAR DECIMAL(16, 4) default 0 not null,
REL_2W_VAR DECIMAL(16, 4) default 0 not null,
	DECISION varchar(16) default '0' not null comment '决策',
	VERSION int not null default 0 comment '版本',
	UPDATED  TIMESTAMP not null default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	CREATED DATETIME NOT NULL DEFAULT '1970-01-01' COMMENT '创建时间',
	KEY `IDX_STOCK_CODE` (`STOCK_CODE`)

)
comment '股票历史信息'
;
drop TABLE  IF EXISTS HIST_DATA_60;

create table HIST_DATA_60
(
	ID bigint not null auto_increment comment '自增主键' primary key,
	STOCK_CODE varchar(16) default '0' not null comment '代码',
	DATE_IN DATETIME default '1970-01-01' not null comment '日期',
	DAY_IN DATE default '1000-01-01' not null comment '日期',
	OPEN DECIMAL(16, 3) default 0 not null comment '开盘价',
	HIGH DECIMAL(16, 3) default 0 not null comment '最高价',
	CLOSE DECIMAL(16, 3) default 0 not null comment '收盘价',
	LOW DECIMAL(16, 3) default 0 not null comment '最低价',
	VOLUME DECIMAL(10, 2) default 0 not null comment '成交量',
	PRIVE_CHANGE DECIMAL(10, 2) default 0 not null comment '价格变动',
	P_CHANGE DECIMAL(16, 2) default 0 not null comment '涨跌幅',
	MA5 DECIMAL(16, 4) default 0 not null comment '5日均价',
	MA10 DECIMAL(16, 4) default 0 not null comment '10日均价',
	MA20 DECIMAL(16, 4) default 0 not null comment '20日均价',
	V_MA5 DECIMAL(10, 2) default 0 not null comment '5日均量',
	V_MA10 DECIMAL(16, 2) default 0 not null comment '10日均量',
	V_MA20 DECIMAL(16, 2) default 0 not null comment '20日均量',
	TURN_OVER DECIMAL(8, 2) default 0 not null comment '换手率',
	MIN_PRICE DECIMAL(16, 4) default 0 not null,
MAX_PRICE DECIMAL(16, 4) default 0 not null,
VAR_PRICE DECIMAL(16, 4) default 0 not null,
VAR_PRICE_3D DECIMAL(16, 4) default 0 not null,
MA30 DECIMAL(16, 4) default 0 not null,
MA60 DECIMAL(16, 4) default 0 not null,
VMA30 DECIMAL(16, 4) default 0 not null,
VMA60 DECIMAL(16, 4) default 0 not null,
MID_PRICE DECIMAL(16, 4) default 0 not null,
OPEN_DEV_MA5 DECIMAL(16, 4) default 0 not null,
OPEN_DEV_MA10 DECIMAL(16, 4) default 0 not null,
CLOSE_DEV_MA5 DECIMAL(16, 4) default 0 not null,
CLOSE_DEV_MA10 DECIMAL(16, 4) default 0 not null,
DIFF DECIMAL(16, 4) default 0 not null,
DEA DECIMAL(16, 4) default 0 not null,
MACD DECIMAL(16, 4) default 0 not null,
BOLL_LOW DECIMAL(16, 4) default 0 not null,
BOLL_UP DECIMAL(16, 4) default 0 not null,
BOLL_RELATIVE DECIMAL(16, 4) default 0 not null,
DIVIDEND_IND DECIMAL(16, 4) default 0 not null,
REL_1Y DECIMAL(16, 4) default 0 not null,
REL_6M DECIMAL(16, 4) default 0 not null,
REL_3M DECIMAL(16, 4) default 0 not null,
REL_1M DECIMAL(16, 4) default 0 not null,
REL_2W DECIMAL(16, 4) default 0 not null,
REL_5D DECIMAL(16, 4) default 0 not null,
EMA5 DECIMAL(16, 4) default 0 not null,
EMA10 DECIMAL(16, 4) default 0 not null,
EMA20 DECIMAL(16, 4) default 0 not null,
EMA30 DECIMAL(16, 4) default 0 not null,
EMA60 DECIMAL(16, 4) default 0 not null,
MA_RANGE DECIMAL(16, 4) default 0 not null,
EMA60_POS DECIMAL(16, 4) default 0 not null,
V_DIFF0 DECIMAL(16, 4) default 0 not null,
V_DIFF1 DECIMAL(16, 4) default 0 not null,
V_DIFF2 DECIMAL(16, 4) default 0 not null,
V_DIFF3 DECIMAL(16, 4) default 0 not null,
V_DIFF4 DECIMAL(16, 4) default 0 not null,
V_DIFF5 DECIMAL(16, 4) default 0 not null,
RSI DECIMAL(16, 4) default 0 not null,
REL_1M_V DECIMAL(16, 4) default 0 not null,
REL_2W_V DECIMAL(16, 4) default 0 not null,
REL_5D_V DECIMAL(16, 4) default 0 not null,
REL_8W_VAR DECIMAL(16, 4) default 0 not null,
REL_4W_VAR DECIMAL(16, 4) default 0 not null,
REL_2W_VAR DECIMAL(16, 4) default 0 not null,
	DECISION varchar(16) default '0' not null comment '决策',
	VERSION int not null default 0 comment '版本',
	UPDATED  TIMESTAMP not null default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	CREATED DATETIME NOT NULL DEFAULT '1970-01-01' COMMENT '创建时间',
	KEY `IDX_STOCK_CODE` (`STOCK_CODE`)

)
comment '股票历史信息'
;

drop TABLE  IF EXISTS DECISION;
create table DECISION
(
	ID bigint not null auto_increment comment '自增主键' primary key,
	STOCK_CODE varchar(16) default '0' not null comment '代码',
	DATE_IN DATETIME default '1970-01-01' not null comment '日期',
	DECISION_TYPE int default 0 not null comment '决策类型：1-天；2-小时',
	HOUR DECIMAL(16, 3) default 0 not null comment '小时，默认为0',
	DECISION varchar(16) default '0' not null comment '决策',
	UPDATED  TIMESTAMP not null default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	CREATED DATETIME NOT NULL DEFAULT '1970-01-01' COMMENT '创建时间',
	KEY `IDX_STOCK_CODE` (`STOCK_CODE`, `DATE_IN`)

)
comment '股票历史信息'
;